Fint drosjeloyve
FINTLabs/helm-charts pull request #3
Opened 2021-11-30 09:55 UTC by erlingjahr

2021-12-01 07:46 UTC, fsjovatsen requested changes
This service also needs the following services:
* fint-altinn-ebevis-service
* fint-altinn-download-queue-service
* fint-drosjeloyve-admin

2021-12-01 07:46 UTC, fsjovatsen commented on charts/fint-drosjeloyve/Chart.yaml
> +description: A Helm chart for Kubernetes
Add a more descriptive description

2021-12-01 07:46 UTC, fsjovatsen commented on charts/fint-drosjeloyve/templates/deployment.yaml
> +  name: {{ .Values.name}}
use `fint-drosjeloyve.name` helper

2021-12-01 07:46 UTC, fsjovatsen commented on charts/fint-drosjeloyve/templates/deployment.yaml
> +              port: 8080
move this to a value

2021-12-01 13:26 UTC, erlingjahr commented on charts/fint-drosjeloyve/templates/deployment.yaml
> +  name: {{ .Values.name}}
Endra

2021-12-01 13:26 UTC, erlingjahr commented on charts/fint-drosjeloyve/templates/deployment.yaml
> +              port: 8080
Flytta til values

2021-12-02 11:13 UTC, mmedalen reviewed
I would use several different value files instead of putting all the municipalities in the same value file.

2021-12-06 09:05 UTC, merged